server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-map
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-map?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: root
    username: root
amap:
  key: 939bdf7ad9118eb692326d00f1303b35